import React, { useEffect, useState, useCallback, useRef, useMemo } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../../hooks/useAuth';
import api from '../../services/api';
import { menuData } from '../../data/menuData';
import type { MenuItem, ApiResponse, CartItem, PaymentMethod, OrderType, Order, OrderStatus } from '../../types';
import { SALES_CHANNELS, channelToOrderType, channelDefaultCustomerName } from '../../utils/salesChannels';
import type { SalesChannel } from '../../utils/salesChannels';
import PaymentModal from '../../components/admin/PaymentModal';
import type { PaymentDetails } from '../../utils/paymentUtils';

interface POSCartItem extends CartItem { line_total: number; person: number; }
interface CustomerMatch { _id: string; name: string; phone: string; email?: string; address?: string; total_orders?: number; }
const TICKET_HEADER = `Sushi Queen\nJose Tomas Cuellar 39 Loc. 1-C\nEdna Garcia\nRFC: GAGE620314GG02\nTEL: 5589905396`;
const TICKET_FOOTER = `Agradecemos tu preferencia, propina no incluida.\nEste documento no es valido como factura.\n¡Gracias por elegir Sushi Queen!`;
const fmt = (n: number) => `${n.toLocaleString('es-MX', { minimumFractionDigits: 0 })}`;
const statusLbl: Record<string, string> = { pending:'Pendiente', confirmed:'Confirmada', preparing:'En cocina', ready:'Lista', delivering:'En camino', delivered:'Cerrada', cancelled:'Cancelada' };

const POS: React.FC = () => {
  const { isAuthenticated } = useAuth();
  const navigate = useNavigate();
  const [items, setItems] = useState<MenuItem[]>([]); const [loading, setLoading] = useState(true); const [category, setCategory] = useState('');
  const [cart, setCart] = useState<POSCartItem[]>([]); const [customerName, setCustomerName] = useState(''); const [customerPhone, setCustomerPhone] = useState(''); const [customerAddress, setCustomerAddress] = useState(''); const [customerEmail, setCustomerEmail] = useState('');
  const [guestCount, setGuestCount] = useState(2); const [orderType, setOrderType] = useState<OrderType>('dine_in'); const [paymentMethod, setPaymentMethod] = useState<PaymentMethod>('cash');
  const [submitting, setSubmitting] = useState(false); const [lastOrder, setLastOrder] = useState<string | null>(null); const [search, setSearch] = useState('');
  const [tables, setTables] = useState<{ _id: string; number: number; zone: string; status: string; capacity: number; shape?: string; size?: string; position_x?: number; position_y?: number }[]>([]);
  const [selectedTable, setSelectedTable] = useState(''); const [selectedTableNum, setSelectedTableNum] = useState(0); const [activeZone, setActiveZone] = useState('Salón');
  const [customerMatches, setCustomerMatches] = useState<CustomerMatch[]>([]); const [showMatches, setShowMatches] = useState(false);
  const [sentToKitchen, setSentToKitchen] = useState(false); const [showTicket, setShowTicket] = useState(false); const [showPayment, setShowPayment] = useState(false);
  const ticketRef = useRef<HTMLDivElement>(null);
  const [tableCarts, setTableCarts] = useState<Record<string, { items: POSCartItem[]; guestCount: number; sent: boolean }>>({});
  const [activeChannel, setActiveChannel] = useState<SalesChannel>('tables');
  const [cashReceived, setCashReceived] = useState(''); const [tipAmount, setTipAmount] = useState('');
  const [cardType, setCardType] = useState<'debit' | 'credit'>('debit'); const [cardLast4, setCardLast4] = useState(''); const [cardApproval, setCardApproval] = useState(''); const [transferNumber, setTransferNumber] = useState('');
  const [showPaymentModal, setShowPaymentModal] = useState(false); const [pendingPaymentDetails, setPendingPaymentDetails] = useState<PaymentDetails | null>(null);
  const [channelOrders, setChannelOrders] = useState<Order[]>([]); const [selectedBoardOrder, setSelectedBoardOrder] = useState<Order | null>(null);
  const [creatingNewOrder, setCreatingNewOrder] = useState(false); const [productSearch, setProductSearch] = useState('');
  const [showCloseModal, setShowCloseModal] = useState(false); const [closePayMethod, setClosePayMethod] = useState<PaymentMethod>('cash'); const [closePayAmount, setClosePayAmount] = useState(''); const [closeTipAmount, setCloseTipAmount] = useState('');
  const [showProductPopup, setShowProductPopup] = useState(false); const [popupCategory, setPopupCategory] = useState('');
  const [expressComment, setExpressComment] = useState('');
  const [showNewCustomerModal, setShowNewCustomerModal] = useState(false);
  const [newCustName, setNewCustName] = useState(''); const [newCustPhone, setNewCustPhone] = useState(''); const [newCustEmail, setNewCustEmail] = useState(''); const [newCustBirthday, setNewCustBirthday] = useState(''); const [newCustRFC, setNewCustRFC] = useState(''); const [newCustComment, setNewCustComment] = useState('');
  useEffect(() => { if (!isAuthenticated) navigate('/admin/login'); }, [isAuthenticated, navigate]);
  const imageByName = useRef<Record<string, string>>(Object.fromEntries(menuData.filter(i => i.image_url).map(i => [i.name.toLowerCase(), i.image_url])));
  const enrichImages = useCallback((list: MenuItem[]): MenuItem[] => list.map(item => (!item.image_url && imageByName.current[item.name.toLowerCase()]) ? { ...item, image_url: imageByName.current[item.name.toLowerCase()] } : item), []);
  const fetchMenu = useCallback(async () => { try { setLoading(true); const { data } = await api.get<ApiResponse<MenuItem[]>>('/admin/menu'); const l = Array.isArray(data.data) ? data.data.filter(i => i.available) : []; setItems(l.length > 0 ? enrichImages(l) : menuData); } catch { setItems(menuData); } finally { setLoading(false); } }, [enrichImages]);
  const fetchTables = async () => { try { const { data } = await api.get('/admin/tables'); setTables(Array.isArray(data.data) ? data.data : []); } catch { setTables([]); } };
  const fetchChannelOrders = useCallback(async (ch: SalesChannel) => { if (ch === 'tables' || ch === 'express') return; const tp: Record<string, string> = { counter:'takeout', delivery:'delivery' }; try { const { data } = await api.get('/admin/orders', { params: { type: tp[ch], channel: ch, per_page: 100 } }); setChannelOrders(Array.isArray(data.data) ? data.data : []); } catch { setChannelOrders([]); } }, []);
  useEffect(() => { if (isAuthenticated) { fetchMenu(); fetchTables(); const iv = setInterval(fetchTables, 10000); return () => clearInterval(iv); } }, [fetchMenu, isAuthenticated]);
  useEffect(() => { if (isAuthenticated && activeChannel !== 'tables' && activeChannel !== 'express') { fetchChannelOrders(activeChannel); const iv = setInterval(() => fetchChannelOrders(activeChannel), 8000); return () => clearInterval(iv); } }, [isAuthenticated, activeChannel, fetchChannelOrders]);

  const selectTable = (t: typeof tables[0]) => { if (selectedTable && cart.length > 0) setTableCarts(p => ({ ...p, [selectedTable]: { items: cart, guestCount, sent: sentToKitchen } })); const saved = tableCarts[t._id]; setCart(saved?.items || []); setGuestCount(saved?.guestCount || 2); setSentToKitchen(saved?.sent || false); setSelectedTable(t._id); setSelectedTableNum(t.number); setOrderType('dine_in'); setShowPayment(false); };
  const goBackToGrid = () => { if (selectedTable && cart.length > 0) setTableCarts(p => ({ ...p, [selectedTable]: { items: cart, guestCount, sent: sentToKitchen } })); setSelectedTable(''); setSelectedTableNum(0); setShowPayment(false); };
  const clearTable = () => { setTableCarts(p => { const n = { ...p }; delete n[selectedTable]; return n; }); setSelectedTable(''); setSelectedTableNum(0); setCart([]); setSentToKitchen(false); setShowPayment(false); resetPay(); setPendingPaymentDetails(null); };
  const tableHasItems = (id: string) => id === selectedTable ? cart.length > 0 : !!tableCarts[id]?.items?.length;
  const resetPay = () => { setCashReceived(''); setTipAmount(''); setCardType('debit'); setCardLast4(''); setCardApproval(''); setTransferNumber(''); };
  const switchChannel = (ch: SalesChannel) => { setActiveChannel(ch); setShowPayment(false); setOrderType(channelToOrderType(ch)); setCreatingNewOrder(false); setSelectedBoardOrder(null); setCart([]); setExpressComment(''); if (ch !== 'tables') { setSelectedTable(''); setSelectedTableNum(0); } };
  const zones = [...new Set(tables.map(t => t.zone))]; const zoneTables = tables.filter(t => t.zone === activeZone).sort((a, b) => a.number - b.number);
  const hasPositions = zoneTables.some(t => t.position_x != null && t.position_y != null);
  const maxTables = zoneTables.length;
  const gridCols = hasPositions ? Math.max(...zoneTables.map(t => (t.position_x ?? 0) + 1), 1) : (maxTables <= 4 ? 2 : maxTables <= 9 ? 3 : maxTables <= 16 ? 4 : maxTables <= 25 ? 5 : 6);
  const gridRows = hasPositions ? Math.max(...zoneTables.map(t => (t.position_y ?? 0) + 1), 1) : undefined;

  const searchCustomers = async (term: string) => { if (term.length < 1) { setCustomerMatches([]); setShowMatches(false); return; } try { const { data } = await api.get(`/admin/customers?search=${encodeURIComponent(term)}`); const matches = Array.isArray(data.data) ? data.data.slice(0, 10) : []; setCustomerMatches(matches); setShowMatches(true); } catch { setCustomerMatches([]); } };
  const selectCustomer = (c: CustomerMatch) => { setCustomerName(c.name); setCustomerPhone(c.phone || ''); if (c.email) setCustomerEmail(c.email); if (c.address) setCustomerAddress(c.address); setShowMatches(false); };
  const categories = [...new Set(items.map(i => i.category))].sort();
  const filtered = items.filter(i => { if (category && i.category !== category) return false; if (search && !i.name.toLowerCase().includes(search.toLowerCase())) return false; return true; });
  const productResults = useMemo(() => { if (!productSearch || productSearch.length < 2) return []; const q = productSearch.toLowerCase(); return items.filter(i => i.name.toLowerCase().includes(q)).slice(0, 8); }, [productSearch, items]);
  const popupFiltered = useMemo(() => { if (!popupCategory) return items; return items.filter(i => i.category === popupCategory); }, [popupCategory, items]);

  const addToCart = (item: MenuItem) => { setCart(prev => { const ex = prev.find(c => c.menu_item_id === item._id && c.person === 1); if (ex) return prev.map(c => c.menu_item_id === item._id && c.person === 1 ? { ...c, quantity: c.quantity + 1, line_total: (c.quantity + 1) * c.price } : c); return [...prev, { menu_item_id: item._id, name: item.name, quantity: 1, price: item.price, modifiers: [], line_total: item.price, person: 1 }]; }); setProductSearch(''); setShowProductPopup(false); };
  const updateQty = (id: string, person: number, delta: number) => { setCart(prev => prev.map(c => c.menu_item_id === id && c.person === person ? { ...c, quantity: c.quantity + delta, line_total: (c.quantity + delta) * c.price } : c).filter(c => c.quantity > 0)); };
  const removeFromCart = (idx: number) => { setCart(prev => prev.filter((_, i) => i !== idx)); };
  const changePerson = (id: string, old: number, nw: number) => { setCart(prev => prev.map(c => c.menu_item_id === id && c.person === old ? { ...c, person: nw } : c)); };
  const total = cart.reduce((s, c) => s + c.line_total, 0); const tip = parseFloat(tipAmount) || 0; const cashChange = (parseFloat(cashReceived) || 0) - total - tip;
  const canClose = () => { if (paymentMethod === 'cash') return parseFloat(cashReceived) >= total; if (paymentMethod === 'card') return cardLast4.length === 4 && cardApproval.length > 0; if (paymentMethod === 'transfer') return transferNumber.length > 0; return false; };
  const canSubmit = () => { if (cart.length === 0 || submitting) return false; if (activeChannel === 'tables' && orderType === 'dine_in') return !!selectedTable; if (activeChannel === 'counter' || activeChannel === 'express') return true; if (orderType === 'takeout') return !!customerName && !!customerPhone; if (orderType === 'delivery') return !!customerName && !!customerPhone && !!customerAddress; return false; };
  const sendToKitchen = async () => {
    if (!canSubmit()) return;
    if (orderType !== 'dine_in' && !pendingPaymentDetails && activeChannel === 'tables') { setShowPaymentModal(true); return; }
    try { setSubmitting(true);
      const pl: Record<string, unknown> = { customer: { name: customerName || channelDefaultCustomerName(activeChannel, selectedTableNum), phone: customerPhone || '', email: customerEmail || '', address: customerAddress }, items: cart.map(c => ({ menu_item_id: c.menu_item_id, name: c.name, price: c.price, quantity: c.quantity, modifiers: [], person: c.person })), source: 'pos', type: orderType, payment_method: paymentMethod, table_id: selectedTable || undefined, guest_count: orderType === 'dine_in' ? guestCount : undefined, channel: activeChannel, notes: expressComment || undefined };
      if (pendingPaymentDetails) pl.payment_details = pendingPaymentDetails;
      await api.post('/orders', pl).catch(() => {});
      setSentToKitchen(true); setPendingPaymentDetails(null);
      if (selectedTable) { setTableCarts(p => ({ ...p, [selectedTable]: { items: cart, guestCount, sent: true } })); setSelectedTable(''); setSelectedTableNum(0); }
      setLastOrder('OK'); setTimeout(() => setLastOrder(null), 3000);
      if (activeChannel !== 'tables') { fetchChannelOrders(activeChannel); setCreatingNewOrder(false); setCart([]); setExpressComment(''); }
    } finally { setSubmitting(false); }
  };
  const handlePaymentConfirm = (d: PaymentDetails) => { setPendingPaymentDetails(d); setShowPaymentModal(false); if (d.method === 'cash') setPaymentMethod('cash'); else setPaymentMethod('card'); };
  useEffect(() => { if (pendingPaymentDetails && !submitting) sendToKitchen(); // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [pendingPaymentDetails]);
  const closeOrder = () => { try { const saved = JSON.parse(localStorage.getItem('pos_completed_orders') || '[]'); saved.unshift({ _id: String(Date.now()), order_number: Date.now() % 100000, items: cart, total, subtotal: total, tax: 0, status: 'completed', source: 'pos', type: orderType, payment_method: paymentMethod, tip, table_id: selectedTable, created_at: new Date().toISOString(), updated_at: new Date().toISOString() }); localStorage.setItem('pos_completed_orders', JSON.stringify(saved.slice(0, 100))); } catch { /* */ } clearTable(); setCustomerName(''); setCustomerPhone(''); setCustomerAddress(''); setCustomerEmail(''); setShowTicket(false); setShowPayment(false); resetPay(); };
  const closeBoardOrder = async () => { if (!selectedBoardOrder) return; try { await api.patch(`/admin/orders/${selectedBoardOrder._id}`, { status: 'delivered', payment_method: closePayMethod, tip: parseFloat(closeTipAmount) || 0 }); } catch { /* */ } setShowCloseModal(false); setSelectedBoardOrder(null); setCloseTipAmount(''); setClosePayAmount(''); fetchChannelOrders(activeChannel); };
  const updateBoardStatus = async (id: string, s: OrderStatus) => { try { await api.patch(`/admin/orders/${id}`, { status: s }); } catch { /* */ } fetchChannelOrders(activeChannel); };
  const saveNewCustomer = async () => { if (!newCustName) return; try { await api.post('/admin/customers', { name: newCustName, phone: newCustPhone, email: newCustEmail, birthday: newCustBirthday || undefined, rfc: newCustRFC || undefined, notes: newCustComment || undefined }); } catch { /* */ } setCustomerName(newCustName); setCustomerPhone(newCustPhone); setCustomerEmail(newCustEmail); setShowNewCustomerModal(false); setNewCustName(''); setNewCustPhone(''); setNewCustEmail(''); setNewCustBirthday(''); setNewCustRFC(''); setNewCustComment(''); };
  const now = new Date(); const dateStr = now.toLocaleDateString('es-MX', { day: '2-digit', month: '2-digit', year: 'numeric' }); const timeStr = now.toLocaleTimeString('es-MX', { hour: '2-digit', minute: '2-digit' });

  // Mostrador: Pendiente, En curso, A entregar, Cerradas (10)
  const counterPending = useMemo(() => channelOrders.filter(o => o.status === 'pending' || o.status === 'confirmed'), [channelOrders]);
  const counterInProgress = useMemo(() => channelOrders.filter(o => o.status === 'preparing'), [channelOrders]);
  const counterReady = useMemo(() => channelOrders.filter(o => o.status === 'ready'), [channelOrders]);
  const counterClosed = useMemo(() => channelOrders.filter(o => o.status === 'delivered').slice(0, 10), [channelOrders]);
  // Delivery: Pendientes, En preparación, Listo para entregar, Enviados, Entregados (50)
  const deliveryPending = useMemo(() => channelOrders.filter(o => o.status === 'pending' || o.status === 'confirmed'), [channelOrders]);
  const deliveryPrep = useMemo(() => channelOrders.filter(o => o.status === 'preparing'), [channelOrders]);
  const deliveryReady = useMemo(() => channelOrders.filter(o => o.status === 'ready'), [channelOrders]);
  const deliverySent = useMemo(() => channelOrders.filter(o => o.status === 'delivering'), [channelOrders]);
  const deliveryDone = useMemo(() => channelOrders.filter(o => o.status === 'delivered').slice(0, 50), [channelOrders]);

  if (showTicket) return (
    <div className="min-h-screen bg-gray-100 flex items-center justify-center p-4 print:bg-white print:p-0"><div className="bg-white max-w-sm w-full shadow-xl rounded-xl print:shadow-none print:rounded-none"><div ref={ticketRef} className="p-6 font-mono text-sm print:p-2" style={{ maxWidth: 300, margin: '0 auto' }}><div className="text-center mb-4"><img src="/images/logo.png" alt="SQ" className="w-16 h-16 mx-auto mb-2" />{TICKET_HEADER.split('\n').map((l, i) => <p key={i} className="text-xs">{l}</p>)}</div><div className="border-t border-dashed border-gray-400 my-2" /><div className="flex justify-between text-xs"><span>Fecha: {dateStr}</span><span>Hora: {timeStr}</span></div>{selectedTableNum > 0 && <p className="text-xs">Mesa: {selectedTableNum} | Personas: {guestCount}</p>}{customerName && <p className="text-xs">Cliente: {customerName}</p>}<div className="border-t border-dashed border-gray-400 my-2" /><table className="w-full text-xs"><thead><tr className="border-b border-gray-300"><th className="text-left py-1">Cant</th><th className="text-left py-1">Producto</th><th className="text-right py-1">Precio</th></tr></thead><tbody>{cart.map((c, i) => (<tr key={i} className="border-b border-gray-100"><td className="py-1">{c.quantity}</td><td className="py-1">{c.name}</td><td className="py-1 text-right">{fmt(c.line_total)}</td></tr>))}</tbody></table><div className="border-t border-dashed border-gray-400 my-2" /><div className="flex justify-between font-bold text-base"><span>TOTAL</span><span>{fmt(total)}</span></div>{tip > 0 && <div className="flex justify-between text-xs"><span>Propina</span><span>{fmt(tip)}</span></div>}<p className="text-xs mt-1">Pago: {paymentMethod === 'cash' ? 'Efectivo' : paymentMethod === 'card' ? `Tarjeta ${cardType === 'credit' ? 'Crédito' : 'Débito'} ****${cardLast4}` : `Transferencia #${transferNumber}`}</p>{paymentMethod === 'cash' && cashChange >= 0 && <p className="text-xs">Recibido: {fmt(parseFloat(cashReceived) || 0)} | Cambio: {fmt(cashChange)}</p>}<div className="border-t border-dashed border-gray-400 my-3" /><div className="text-center text-xs">{TICKET_FOOTER.split('\n').map((l, i) => <p key={i}>{l}</p>)}</div></div><div className="p-4 border-t flex gap-2 print:hidden"><button onClick={() => setShowTicket(false)} className="flex-1 py-2 rounded-lg border text-sm">Volver</button><button onClick={() => window.print()} className="flex-1 py-2 rounded-lg bg-blue-500 text-white text-sm">🖨 Imprimir</button><button onClick={closeOrder} className="flex-1 py-2 rounded-lg bg-green-500 text-white text-sm">✓ Cerrar</button></div></div></div>
  );

  const BoardRow: React.FC<{ o: Order; hoverBg: string }> = ({ o, hoverBg }) => (<tr onClick={() => { setSelectedBoardOrder(o); setCreatingNewOrder(false); }} className={`border-b border-gray-50 cursor-pointer ${hoverBg} ${selectedBoardOrder?._id === o._id ? 'bg-gray-100' : ''}`}><td className="px-3 py-2 font-mono font-bold text-orange-600">#{o.order_number || o._id.slice(-6).toUpperCase()}</td><td className="px-3 py-2 text-xs">{new Date(o.created_at).toLocaleString('es-MX', { day:'2-digit', month:'2-digit', year:'2-digit', hour:'2-digit', minute:'2-digit' })}</td><td className="px-3 py-2 text-xs">{statusLbl[o.status] || o.status}</td><td className="px-3 py-2 text-xs">{(o as any).customer?.name || '—'}</td><td className="px-3 py-2 text-right text-xs font-medium">${fmt(o.total)}</td></tr>);
  const BoardSection: React.FC<{ title: string; orders: Order[]; bg: string; hoverBg: string }> = ({ title, orders, bg, hoverBg }) => (<div><h3 className={`text-xs font-bold ${bg} rounded-t-lg px-3 py-2 border`}>{title}</h3><div className="border border-t-0 rounded-b-lg bg-white"><table className="w-full text-xs"><thead><tr className="border-b border-gray-100 text-gray-500"><th className="text-left px-3 py-2">ID</th><th className="text-left px-3 py-2">Hora</th><th className="text-left px-3 py-2">Estado</th><th className="text-left px-3 py-2">Cliente</th><th className="text-right px-3 py-2">Total</th></tr></thead><tbody>{orders.length === 0 ? <tr><td colSpan={5} className="px-3 py-4 text-center text-gray-400">Sin pedidos</td></tr> : orders.map(o => <BoardRow key={o._id} o={o} hoverBg={hoverBg} />)}</tbody></table></div></div>);

  // Customer autocomplete + new order panel for Mostrador/Delivery
  const CustomerFields: React.FC<{ showEmail?: boolean; showAddress?: boolean }> = ({ showEmail, showAddress }) => (
    <div className="px-4 py-2 border-b space-y-1 relative">
      <input value={customerName} onChange={e => { setCustomerName(e.target.value); searchCustomers(e.target.value); }} placeholder="Cliente *" className="w-full border rounded px-2 py-1 text-xs" />
      <input value={customerPhone} onChange={e => { setCustomerPhone(e.target.value); if (e.target.value.length >= 2) searchCustomers(e.target.value); }} placeholder="Teléfono (opcional)" className="w-full border rounded px-2 py-1 text-xs" />
      {showEmail && <input value={customerEmail} onChange={e => { setCustomerEmail(e.target.value); if (e.target.value.length >= 3) searchCustomers(e.target.value); }} placeholder="Email (opcional)" className="w-full border rounded px-2 py-1 text-xs" />}
      {showAddress && <input value={customerAddress} onChange={e => setCustomerAddress(e.target.value)} placeholder="Dirección *" className="w-full border rounded px-2 py-1 text-xs" />}
      {showMatches && customerMatches.length > 0 && <div className="absolute z-20 left-4 right-4 bg-white border rounded-lg shadow-lg max-h-48 overflow-y-auto">
        {customerMatches.map(c => <button key={c._id} onClick={() => selectCustomer(c)} className="w-full text-left px-3 py-2 hover:bg-orange-50 text-xs border-b last:border-0"><span className="font-medium">{c.name}</span> — {c.phone}{c.email ? ` — ${c.email}` : ''}</button>)}
        <button onClick={() => { setShowNewCustomerModal(true); setNewCustName(customerName); setNewCustPhone(customerPhone); setNewCustEmail(customerEmail); setShowMatches(false); }} className="w-full text-left px-3 py-2 text-blue-600 font-medium text-xs hover:bg-blue-50">+ Nuevo Cliente</button>
      </div>}
    </div>
  );

  return (
    <div className="h-screen bg-gray-100 flex flex-col overflow-hidden">
      {/* ═══ MOSTRADOR EXPRESS: grid de productos con imágenes ═══ */}
      {activeChannel === 'express' ? (
        <div className="flex-1 flex flex-col overflow-hidden">
          <div className="bg-white border-b px-4 py-3 flex items-center gap-3"><button onClick={() => navigate('/admin')} className="text-gray-500 hover:text-gray-700 text-sm">← Admin</button><h1 className="text-lg font-bold text-gray-900">Punto de Venta</h1><input value={search} onChange={e => setSearch(e.target.value)} placeholder="🔍 Buscar..." className="ml-auto border rounded-lg px-3 py-1.5 text-xs w-32 lg:w-48 outline-none" /></div>
          <div className="flex border-b border-gray-200 bg-white">{SALES_CHANNELS.map(ch => (<button key={ch.id} onClick={() => switchChannel(ch.id)} className={`flex-1 py-3 text-sm font-medium ${activeChannel === ch.id ? 'border-b-2 border-sushi-primary text-sushi-primary' : 'text-gray-500 hover:text-gray-700'}`}>{ch.icon} {ch.label}</button>))}</div>
          <div className="bg-white border-b px-4 py-2 flex items-center gap-2 overflow-x-auto"><button onClick={() => setCategory('')} className={`px-3 py-1.5 rounded-full text-xs font-medium whitespace-nowrap ${!category ? 'bg-sushi-primary text-white' : 'bg-gray-100 text-gray-600'}`}>Todos</button>{categories.map(c => <button key={c} onClick={() => setCategory(c)} className={`px-3 py-1.5 rounded-full text-xs font-medium whitespace-nowrap ${category === c ? 'bg-sushi-primary text-white' : 'bg-gray-100 text-gray-600'}`}>{c}</button>)}</div>
          <div className="flex-1 flex overflow-hidden">
            <div className="flex-1 overflow-y-auto p-4">
              {loading ? <div className="flex justify-center py-12"><div className="animate-spin rounded-full h-8 w-8 border-t-2 border-b-2 border-sushi-primary" /></div> : (
                <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-3">
                  {filtered.map(item => (<button key={item._id} onClick={() => addToCart(item)} className="bg-white rounded-xl shadow-sm border p-2 text-left hover:shadow-md transition-all active:scale-95">
                    {item.image_url ? <img src={item.image_url} alt={item.name} className="w-full h-24 object-cover rounded-lg mb-1" onError={e => { (e.target as HTMLImageElement).style.display = 'none'; }} /> : <div className="w-full h-24 bg-gray-100 rounded-lg mb-1 flex items-center justify-center text-xs text-gray-400">Sin imagen</div>}
                    <p className="text-xs font-medium text-gray-900 truncate">{item.name}</p><p className="text-sm font-bold text-sushi-primary">${fmt(item.price)}</p>
                  </button>))}
                </div>
              )}
            </div>
            {/* Right: Express cart */}
            <div className="w-80 border-l bg-white flex flex-col overflow-hidden">
              <div className="px-4 py-3 border-b bg-orange-50"><h3 className="font-bold text-sm">⚡ Mostrador Express</h3></div>
              <div className="px-4 py-2 border-b space-y-1 relative">
                <input value={customerName} onChange={e => { setCustomerName(e.target.value); searchCustomers(e.target.value); }} placeholder="Cliente" className="w-full border rounded px-2 py-1 text-xs" />
                {showMatches && customerMatches.length > 0 && <div className="absolute z-20 left-4 right-4 bg-white border rounded-lg shadow-lg max-h-48 overflow-y-auto">{customerMatches.map(c => <button key={c._id} onClick={() => selectCustomer(c)} className="w-full text-left px-3 py-2 hover:bg-orange-50 text-xs border-b last:border-0"><span className="font-medium">{c.name}</span> — {c.phone}</button>)}<button onClick={() => { setShowNewCustomerModal(true); setNewCustName(customerName); setShowMatches(false); }} className="w-full text-left px-3 py-2 text-blue-600 font-medium text-xs hover:bg-blue-50">+ Nuevo Cliente</button></div>}
                <textarea value={expressComment} onChange={e => setExpressComment(e.target.value)} placeholder="Comentario" className="w-full border rounded px-2 py-1 text-xs" rows={2} />
              </div>
              <div className="flex-1 overflow-y-auto px-4 py-2 space-y-1">{cart.map((item, idx) => (<div key={idx} className="flex items-center justify-between text-sm py-1 border-b border-gray-100"><div className="flex items-center gap-2"><button onClick={() => updateQty(item.menu_item_id, item.person, -1)} className="text-orange-500 font-bold">−</button><span className="w-5 text-center font-medium">{item.quantity}</span><button onClick={() => updateQty(item.menu_item_id, item.person, 1)} className="text-orange-500 font-bold">+</button><span className="text-gray-800 truncate text-xs">{item.name}</span></div><div className="flex items-center gap-2 flex-shrink-0"><span className="text-gray-600 text-xs">${fmt(item.line_total)}</span><button onClick={() => removeFromCart(idx)} className="text-gray-400 hover:text-red-500">×</button></div></div>))}</div>
              <div className="border-t px-4 py-3"><div className="flex justify-between mb-2"><span className="text-sm text-gray-600">Total:</span><span className="text-lg font-bold">${fmt(total)}</span></div><button onClick={sendToKitchen} disabled={cart.length === 0 || submitting} className="w-full py-2 rounded-lg bg-orange-500 hover:bg-orange-600 disabled:opacity-50 text-white text-sm font-bold">{submitting ? 'Enviando...' : '🍳 Confirmar'}</button></div>
              {lastOrder && <div className="px-4 pb-2"><div className="bg-green-50 border border-green-200 rounded-lg px-3 py-2 text-center"><p className="text-green-700 text-xs font-medium">Pedido enviado ✓</p></div></div>}
            </div>
          </div>
        </div>
      ) : activeChannel === 'counter' || activeChannel === 'delivery' ? (
        /* ═══ MOSTRADOR / DELIVERY: Fudo board ═══ */
        <div className="flex-1 flex flex-col overflow-hidden">
          <div className="bg-white border-b px-4 py-3 flex items-center gap-3"><button onClick={() => navigate('/admin')} className="text-gray-500 hover:text-gray-700 text-sm">← Admin</button><h1 className="text-lg font-bold text-gray-900">Punto de Venta</h1></div>
          <div className="flex border-b border-gray-200 bg-white">{SALES_CHANNELS.map(ch => (<button key={ch.id} onClick={() => switchChannel(ch.id)} className={`flex-1 py-3 text-sm font-medium ${activeChannel === ch.id ? 'border-b-2 border-sushi-primary text-sushi-primary' : 'text-gray-500 hover:text-gray-700'}`}>{ch.icon} {ch.label}</button>))}</div>
          <div className="flex-1 flex overflow-hidden">
            <div className="flex-1 overflow-y-auto p-4 space-y-4">
              <div className="flex items-center justify-between"><h2 className="text-sm font-bold text-gray-700 uppercase">{activeChannel === 'counter' ? 'MOSTRADOR' : 'DELIVERY'}</h2><button onClick={() => { setCreatingNewOrder(true); setSelectedBoardOrder(null); setCart([]); setProductSearch(''); setCustomerName(''); setCustomerPhone(''); setCustomerEmail(''); setCustomerAddress(''); }} className="bg-orange-500 hover:bg-orange-600 text-white px-4 py-2 rounded-lg text-sm font-medium">+ Nuevo Pedido</button></div>
              {activeChannel === 'counter' ? (<>
                <BoardSection title="PENDIENTE" orders={counterPending} bg="text-yellow-800 bg-yellow-50 border-yellow-200" hoverBg="hover:bg-yellow-50" />
                <BoardSection title="EN CURSO" orders={counterInProgress} bg="text-blue-800 bg-blue-50 border-blue-200" hoverBg="hover:bg-blue-50" />
                <BoardSection title="A ENTREGAR" orders={counterReady} bg="text-green-800 bg-green-50 border-green-200" hoverBg="hover:bg-green-50" />
                <BoardSection title="CERRADAS (ÚLTIMAS 10)" orders={counterClosed} bg="text-gray-600 bg-gray-50 border-gray-200" hoverBg="hover:bg-gray-50" />
              </>) : (<>
                <BoardSection title="PENDIENTES" orders={deliveryPending} bg="text-yellow-800 bg-yellow-50 border-yellow-200" hoverBg="hover:bg-yellow-50" />
                <BoardSection title="EN PREPARACIÓN" orders={deliveryPrep} bg="text-blue-800 bg-blue-50 border-blue-200" hoverBg="hover:bg-blue-50" />
                <BoardSection title="LISTO PARA ENTREGAR" orders={deliveryReady} bg="text-green-800 bg-green-50 border-green-200" hoverBg="hover:bg-green-50" />
                <BoardSection title="ENVIADOS" orders={deliverySent} bg="text-indigo-800 bg-indigo-50 border-indigo-200" hoverBg="hover:bg-indigo-50" />
                <BoardSection title="ENTREGADOS (ÚLTIMOS 50)" orders={deliveryDone} bg="text-gray-600 bg-gray-50 border-gray-200" hoverBg="hover:bg-gray-50" />
              </>)}
            </div>
            <div className="w-80 border-l border-gray-200 bg-white flex flex-col overflow-hidden">
              {creatingNewOrder ? (
                <div className="flex flex-col h-full">
                  <div className="px-4 py-3 border-b bg-orange-50"><h3 className="font-bold text-sm">Nuevo Pedido</h3><p className="text-xs text-gray-500">{timeStr}</p></div>
                  <CustomerFields showEmail={true} showAddress={activeChannel === 'delivery'} />
                  <div className="px-4 py-2 border-b"><div className="flex items-center gap-2 bg-gray-900 text-white rounded-t-lg px-3 py-2"><span className="text-xs font-bold">ADICIONAR</span></div><div className="flex items-center gap-2 border border-t-0 rounded-b-lg px-2 py-1.5 bg-white relative"><button onClick={() => { setShowProductPopup(true); setPopupCategory(''); }} className="w-7 h-7 rounded-full bg-orange-500 text-white flex items-center justify-center text-lg font-bold flex-shrink-0">+</button><input value={productSearch} onChange={e => setProductSearch(e.target.value)} placeholder="Buscar producto..." className="flex-1 text-sm outline-none" />{productResults.length > 0 && <div className="absolute top-full left-0 right-0 bg-white border rounded-b-lg shadow-lg z-10 max-h-48 overflow-y-auto">{productResults.map(item => <button key={item._id} onClick={() => addToCart(item)} className="w-full text-left px-3 py-2 hover:bg-orange-50 text-sm border-b last:border-0 flex justify-between"><span>{item.name}</span><span className="text-gray-500">${fmt(item.price)}</span></button>)}</div>}</div></div>
                  <div className="flex-1 overflow-y-auto px-4 py-2 space-y-1">{cart.map((item, idx) => (<div key={idx} className="flex items-center justify-between text-sm py-1 border-b border-gray-100"><div className="flex items-center gap-2"><button onClick={() => updateQty(item.menu_item_id, item.person, -1)} className="text-orange-500 font-bold">−</button><span className="w-5 text-center font-medium">{item.quantity}</span><button onClick={() => updateQty(item.menu_item_id, item.person, 1)} className="text-orange-500 font-bold">+</button><span className="text-gray-800 truncate text-xs">{item.name}</span></div><div className="flex items-center gap-2 flex-shrink-0"><span className="text-gray-600 text-xs">${fmt(item.line_total)}</span><button onClick={() => removeFromCart(idx)} className="text-gray-400 hover:text-red-500">×</button></div></div>))}</div>
                  <div className="border-t px-4 py-3"><div className="flex justify-between mb-2"><span className="text-sm text-gray-600">Total a confirmar:</span><span className="text-lg font-bold">${fmt(total)}</span></div><div className="flex gap-2"><button onClick={() => { setCreatingNewOrder(false); setCart([]); }} className="flex-1 py-2 rounded-lg border text-sm text-gray-600">Cancelar</button><button onClick={sendToKitchen} disabled={cart.length === 0 || submitting} className="flex-1 py-2 rounded-lg bg-orange-500 hover:bg-orange-600 disabled:opacity-50 text-white text-sm font-bold">{submitting ? 'Enviando...' : 'Confirmar'}</button></div></div>
                </div>
              ) : selectedBoardOrder ? (
                <div className="flex flex-col h-full">
                  <div className="px-4 py-3 border-b bg-orange-50 flex items-center justify-between"><h3 className="font-bold text-orange-600">ID #{selectedBoardOrder.order_number || selectedBoardOrder._id.slice(-6).toUpperCase()}</h3><button onClick={() => setSelectedBoardOrder(null)} className="text-gray-400 hover:text-gray-600 text-lg">×</button></div>
                  <div className="px-4 py-3 space-y-2 text-sm border-b"><div className="flex justify-between"><span className="text-gray-500">Hora Inicio</span><span>{new Date(selectedBoardOrder.created_at).toLocaleString('es-MX', { day:'2-digit', month:'2-digit', year:'2-digit', hour:'2-digit', minute:'2-digit', second:'2-digit' })}</span></div><div className="flex justify-between"><span className="text-gray-500">Cliente</span><span>{(selectedBoardOrder as any).customer?.name || '—'}</span></div><div className="flex justify-between"><span className="text-gray-500">Estado</span><span className="font-medium">{statusLbl[selectedBoardOrder.status] || selectedBoardOrder.status}</span></div></div>
                  <div className="flex-1 overflow-y-auto px-4 py-2"><p className="text-xs text-gray-500 mb-2">Items:</p>{selectedBoardOrder.items.map((it, i) => <div key={i} className="flex justify-between text-sm py-1 border-b border-gray-50"><span>{it.quantity}x {it.name}</span><span className="text-gray-600">${fmt(it.price * it.quantity)}</span></div>)}</div>
                  <div className="border-t px-4 py-2"><div className="flex justify-between font-bold text-base mb-3"><span>Total</span><span>${fmt(selectedBoardOrder.total)}</span></div>{selectedBoardOrder.status !== 'delivered' && selectedBoardOrder.status !== 'cancelled' && (<div className="space-y-2">
                    {selectedBoardOrder.status === 'pending' && <button onClick={() => updateBoardStatus(selectedBoardOrder._id, 'preparing')} className="w-full py-2 rounded-lg bg-blue-500 text-white text-sm font-medium">🍳 {activeChannel === 'delivery' ? 'En preparación' : 'En curso'}</button>}
                    {selectedBoardOrder.status === 'preparing' && <button onClick={() => updateBoardStatus(selectedBoardOrder._id, 'ready')} className="w-full py-2 rounded-lg bg-green-500 text-white text-sm font-medium">✓ Listo para entregar</button>}
                    {selectedBoardOrder.status === 'ready' && activeChannel === 'delivery' && <button onClick={() => updateBoardStatus(selectedBoardOrder._id, 'delivering')} className="w-full py-2 rounded-lg bg-indigo-500 text-white text-sm font-medium">🛵 Enviado</button>}
                    {((selectedBoardOrder.status === 'ready' && activeChannel === 'counter') || selectedBoardOrder.status === 'delivering') && <button onClick={() => setShowCloseModal(true)} className="w-full py-2 rounded-lg bg-gray-800 text-white text-sm font-medium">Cerrar Pedido</button>}
                  </div>)}</div>
                </div>
              ) : (<div className="flex-1 flex items-center justify-center text-gray-400 text-sm p-4 text-center">Selecciona un pedido o crea uno nuevo</div>)}
            </div>
          </div>
        </div>
      ) : (
        /* ═══ TABLES MODE ═══ */
        <div className="flex-1 flex flex-col lg:flex-row overflow-hidden">
          <div className="flex-1 flex flex-col min-w-0 overflow-hidden">
            <div className="bg-white border-b px-4 py-3 flex items-center gap-3"><button onClick={() => navigate('/admin')} className="text-gray-500 hover:text-gray-700 text-sm">← Admin</button><h1 className="text-lg font-bold text-gray-900">Punto de Venta</h1><input value={search} onChange={e => setSearch(e.target.value)} placeholder="🔍 Buscar..." className="ml-auto border rounded-lg px-3 py-1.5 text-xs w-32 lg:w-48 outline-none" /></div>
            {selectedTable && <div className="bg-white border-b px-4 py-2 flex items-center gap-2 overflow-x-auto"><button onClick={() => setCategory('')} className={`px-3 py-1.5 rounded-full text-xs font-medium whitespace-nowrap ${!category ? 'bg-sushi-primary text-white' : 'bg-gray-100 text-gray-600'}`}>Todos</button>{categories.map(c => <button key={c} onClick={() => setCategory(c)} className={`px-3 py-1.5 rounded-full text-xs font-medium whitespace-nowrap ${category === c ? 'bg-sushi-primary text-white' : 'bg-gray-100 text-gray-600'}`}>{c}</button>)}</div>}
            <div className="flex-1 overflow-y-auto p-4">
              {!selectedTable ? (<div>
                <div className="flex border-b border-gray-200 mb-4">{SALES_CHANNELS.map(ch => <button key={ch.id} onClick={() => switchChannel(ch.id)} className={`flex-1 py-3 text-sm font-medium ${activeChannel === ch.id ? 'border-b-2 border-sushi-primary text-sushi-primary' : 'text-gray-500 hover:text-gray-700'}`}>{ch.icon} {ch.label}</button>)}</div>
                <div className="flex gap-2 mb-4">{zones.map(z => <button key={z} onClick={() => setActiveZone(z)} className={`px-4 py-2 rounded-lg text-sm font-medium ${activeZone === z ? 'bg-white shadow text-gray-900 border' : 'bg-gray-200 text-gray-600'}`}>{z}</button>)}</div>
                {hasPositions ? (<div className="grid gap-2" style={{ gridTemplateColumns: `repeat(${gridCols}, 1fr)`, gridTemplateRows: gridRows ? `repeat(${gridRows}, 1fr)` : undefined }}>{zoneTables.map(t => { const hi = tableHasItems(t._id); const cl = hi ? 'bg-orange-500 text-white' : t.status === 'occupied' ? 'bg-red-500 text-white' : 'bg-green-500 text-white'; return <button key={t._id} onClick={() => selectTable(t)} style={{ gridColumn: (t.position_x ?? 0) + 1, gridRow: (t.position_y ?? 0) + 1 }} className={`${cl} rounded-lg p-3 font-bold text-sm hover:scale-105 transition-transform shadow-md aspect-square flex items-center justify-center`}>{t.number}</button>; })}</div>
                ) : (<div className="grid gap-2" style={{ gridTemplateColumns: `repeat(${gridCols}, 1fr)` }}>{zoneTables.map(t => { const hi = tableHasItems(t._id); const cl = hi ? 'bg-orange-500 text-white' : t.status === 'occupied' ? 'bg-red-500 text-white' : 'bg-green-500 text-white'; return <button key={t._id} onClick={() => selectTable(t)} className={`${cl} rounded-lg p-3 font-bold text-sm hover:scale-105 transition-transform shadow-md aspect-square flex items-center justify-center`}>{t.number}</button>; })}</div>)}
                {lastOrder && <div className="mt-3 bg-green-50 border border-green-200 rounded-lg px-3 py-2 text-center"><p className="text-green-700 text-xs font-medium">Comanda enviada a cocina ✓</p></div>}
              </div>) : loading ? (<div className="flex justify-center py-12"><div className="animate-spin rounded-full h-8 w-8 border-t-2 border-b-2 border-sushi-primary" /></div>
              ) : (<div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-3">{filtered.map(item => <button key={item._id} onClick={() => addToCart(item)} className="bg-white rounded-xl shadow-sm border p-3 text-left hover:shadow-md transition-all active:scale-95"><p className="text-xs font-medium text-gray-900 truncate">{item.name}</p><p className="text-sm font-bold text-sushi-primary">${fmt(item.price)}</p></button>)}</div>)}
            </div>
          </div>
          <div className="w-full lg:w-80 bg-white border-t lg:border-t-0 lg:border-l border-gray-200 flex flex-col max-h-screen lg:max-h-none">
            <div className="px-4 py-3 border-b flex items-center justify-between"><h2 className="font-semibold text-gray-900">{orderType === 'dine_in' && selectedTableNum > 0 ? `Mesa ${selectedTableNum}` : 'Orden Actual'}</h2>{orderType === 'dine_in' && selectedTable && <button onClick={goBackToGrid} className="text-xs text-gray-500 hover:text-red-500">← Mesas</button>}</div>
            <div className="px-4 py-2 border-b"><div className="flex gap-2 overflow-x-auto">{(['dine_in', 'takeout', 'delivery'] as OrderType[]).map(t => <button key={t} onClick={() => { setOrderType(t); if (t !== 'dine_in') { setSelectedTable(''); setSelectedTableNum(0); } setShowPayment(false); }} className={`flex-1 min-w-[80px] py-1.5 rounded-lg text-xs font-medium whitespace-nowrap ${orderType === t ? 'bg-sushi-primary text-white' : 'bg-gray-100 text-gray-600'}`}>{t === 'dine_in' ? 'Mesa' : t === 'takeout' ? 'Para llevar' : 'Delivery'}</button>)}</div></div>
            <div className="px-4 py-2 border-b space-y-2">
              {orderType === 'dine_in' && selectedTable && <div className="flex items-center gap-2"><label className="text-xs text-gray-500">Personas:</label><select value={guestCount} onChange={e => setGuestCount(Number(e.target.value))} className="flex-1 border rounded-lg px-2 py-1 text-xs">{[1,2,3,4,5,6,7,8].map(n => <option key={n} value={n}>{n}</option>)}</select></div>}
              {orderType === 'takeout' && <div className="relative"><input value={customerName} onChange={e => { setCustomerName(e.target.value); searchCustomers(e.target.value); }} placeholder="Nombre *" className="w-full border rounded-lg px-3 py-1.5 text-xs" /><input value={customerPhone} onChange={e => { setCustomerPhone(e.target.value); searchCustomers(e.target.value); }} placeholder="Teléfono *" className="w-full border rounded-lg px-3 py-1.5 text-xs mt-2" />{showMatches && customerMatches.length > 0 && <div className="absolute z-10 w-full bg-white border rounded-lg shadow-lg mt-1 max-h-32 overflow-y-auto">{customerMatches.map(c => <button key={c._id} onClick={() => selectCustomer(c)} className="w-full text-left px-3 py-2 hover:bg-gray-50 text-xs border-b last:border-0"><span className="font-medium">{c.name}</span> — {c.phone}</button>)}</div>}</div>}
              {orderType === 'delivery' && <div className="relative"><input value={customerPhone} onChange={e => { setCustomerPhone(e.target.value); searchCustomers(e.target.value); }} placeholder="Teléfono *" className="w-full border rounded-lg px-3 py-1.5 text-xs" />{showMatches && customerMatches.length > 0 && <div className="absolute z-10 w-full bg-white border rounded-lg shadow-lg mt-1 max-h-32 overflow-y-auto">{customerMatches.map(c => <button key={c._id} onClick={() => selectCustomer(c)} className="w-full text-left px-3 py-2 hover:bg-gray-50 text-xs border-b last:border-0"><span className="font-medium">{c.name}</span> — {c.phone}</button>)}</div>}<input value={customerName} onChange={e => setCustomerName(e.target.value)} placeholder="Nombre *" className="w-full border rounded-lg px-3 py-1.5 text-xs mt-2" /><input value={customerAddress} onChange={e => setCustomerAddress(e.target.value)} placeholder="Dirección *" className="w-full border rounded-lg px-3 py-1.5 text-xs mt-2" /></div>}
            </div>
            <div className="flex-1 overflow-y-auto px-4 py-2 space-y-2">{cart.length === 0 ? <p className="text-center text-gray-400 text-sm py-8">Agrega productos</p> : cart.map((item, idx) => (<div key={`${item.menu_item_id}-${item.person}-${idx}`} className="bg-gray-50 rounded-lg px-3 py-2"><div className="flex items-center justify-between"><div className="flex-1 min-w-0"><p className="text-xs font-medium text-gray-900 truncate">{item.name}</p><p className="text-xs text-gray-500">{fmt(item.price)} c/u</p></div><div className="flex items-center gap-1"><button onClick={() => updateQty(item.menu_item_id, item.person, -1)} className="w-6 h-6 rounded-full bg-gray-200 text-gray-600 text-xs flex items-center justify-center">-</button><span className="text-sm font-bold w-6 text-center">{item.quantity}</span><button onClick={() => updateQty(item.menu_item_id, item.person, 1)} className="w-6 h-6 rounded-full bg-sushi-primary text-white text-xs flex items-center justify-center">+</button></div><p className="text-sm font-bold text-gray-900 ml-2 w-14 text-right">{fmt(item.line_total)}</p></div>{orderType === 'dine_in' && guestCount > 1 && <select value={item.person} onChange={e => changePerson(item.menu_item_id, item.person, Number(e.target.value))} className="mt-1 text-xs border rounded px-2 py-0.5 bg-white text-gray-600">{Array.from({ length: guestCount }, (_, i) => <option key={i + 1} value={i + 1}>Persona {i + 1}</option>)}</select>}</div>))}</div>
            {showPayment && (<div className="border-t px-4 py-2 space-y-2 bg-gray-50"><div className="flex gap-2">{(['cash', 'card', 'transfer'] as PaymentMethod[]).map(m => <button key={m} onClick={() => { setPaymentMethod(m); resetPay(); }} className={`flex-1 py-1.5 rounded-lg text-xs font-medium ${paymentMethod === m ? 'bg-green-500 text-white' : 'bg-gray-100 text-gray-600'}`}>{m === 'cash' ? 'Efectivo' : m === 'card' ? 'Tarjeta' : 'Transferencia'}</button>)}</div>{paymentMethod === 'cash' && <div className="space-y-1"><div className="flex gap-2"><div className="flex-1"><label className="text-xs text-gray-500">Paga con:</label><input type="number" value={cashReceived} onChange={e => setCashReceived(e.target.value)} placeholder="0" className="w-full border rounded-lg px-2 py-1 text-sm" /></div><div className="flex-1"><label className="text-xs text-gray-500">Propina:</label><input type="number" value={tipAmount} onChange={e => setTipAmount(e.target.value)} placeholder="0" className="w-full border rounded-lg px-2 py-1 text-sm" /></div></div>{parseFloat(cashReceived) > 0 && <p className="text-xs font-medium text-center">Cambio: <span className={cashChange >= 0 ? 'text-green-600' : 'text-red-600'}>{fmt(Math.max(0, cashChange))}</span></p>}</div>}{paymentMethod === 'card' && <div className="space-y-1"><div className="flex gap-2"><button onClick={() => setCardType('debit')} className={`flex-1 py-1 rounded text-xs ${cardType === 'debit' ? 'bg-blue-500 text-white' : 'bg-gray-200'}`}>Débito</button><button onClick={() => setCardType('credit')} className={`flex-1 py-1 rounded text-xs ${cardType === 'credit' ? 'bg-blue-500 text-white' : 'bg-gray-200'}`}>Crédito</button></div><div className="flex gap-2"><div className="flex-1"><label className="text-xs text-gray-500">Últimos 4:</label><input maxLength={4} value={cardLast4} onChange={e => setCardLast4(e.target.value.replace(/\D/g, ''))} placeholder="0000" className="w-full border rounded-lg px-2 py-1 text-sm" /></div><div className="flex-1"><label className="text-xs text-gray-500">Aprobación:</label><input value={cardApproval} onChange={e => setCardApproval(e.target.value)} placeholder="######" className="w-full border rounded-lg px-2 py-1 text-sm" /></div></div></div>}{paymentMethod === 'transfer' && <div className="space-y-1"><div><label className="text-xs text-gray-500">No. Transferencia:</label><input value={transferNumber} onChange={e => setTransferNumber(e.target.value)} placeholder="Referencia" className="w-full border rounded-lg px-2 py-1 text-sm" /></div></div>}</div>)}
            <div className="border-t px-4 py-3"><div className="flex justify-between items-center mb-2"><span className="text-sm text-gray-600">Total</span><span className="text-2xl font-bold text-gray-900">${fmt(total)}</span></div>{!sentToKitchen && !showPayment ? (<button onClick={sendToKitchen} disabled={!canSubmit()} className="w-full bg-orange-500 hover:bg-orange-600 disabled:opacity-50 text-white font-bold py-3 rounded-xl text-sm">{submitting ? 'Enviando...' : '🍳 Enviar a cocina'}</button>) : showPayment ? (<div className="space-y-2"><button onClick={() => setShowTicket(true)} className="w-full bg-blue-500 text-white font-bold py-3 rounded-xl text-sm">🧾 Imprimir cuenta</button><button onClick={closeOrder} disabled={!canClose()} className="w-full bg-green-500 disabled:opacity-50 text-white font-bold py-3 rounded-xl text-sm">✓ Cobrar {fmt(total + tip)}</button></div>) : (<div className="space-y-2"><button onClick={sendToKitchen} disabled={!canSubmit()} className="w-full bg-orange-500 disabled:opacity-50 text-white font-bold py-3 rounded-xl text-sm">🍳 Agregar más</button><button onClick={() => setShowPayment(true)} className="w-full bg-green-500 text-white font-bold py-3 rounded-xl text-sm">💰 Pedir cuenta</button></div>)}</div>
          </div>
        </div>
      )}
      {showPaymentModal && <PaymentModal total={total} onConfirm={handlePaymentConfirm} onCancel={() => setShowPaymentModal(false)} />}

      {/* Close order modal */}
      {showCloseModal && selectedBoardOrder && (<div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4"><div className="bg-white rounded-2xl shadow-2xl w-full max-w-md"><div className="px-6 py-4 border-b"><h2 className="text-lg font-bold">Cerrar Pedido #{selectedBoardOrder.order_number || selectedBoardOrder._id.slice(-6).toUpperCase()}</h2><p className="text-sm text-gray-500">Total: <span className="font-bold">${fmt(selectedBoardOrder.total)}</span></p></div><div className="px-6 py-4 space-y-4"><div><label className="block text-xs font-bold text-gray-700 mb-2 uppercase">Propina</label><div className="flex gap-2 items-center"><select className="border rounded-lg px-3 py-2 text-sm"><option value="cash">Efectivo</option><option value="card">Tarjeta</option></select><span className="text-gray-500">$</span><input type="number" value={closeTipAmount} onChange={e => setCloseTipAmount(e.target.value)} placeholder="0" className="flex-1 border rounded-lg px-3 py-2 text-sm" /><button onClick={() => setCloseTipAmount('')} className="text-gray-400 hover:text-red-500">×</button></div></div><div><label className="block text-xs font-bold text-gray-700 mb-2 uppercase">Pago</label><div className="flex gap-2 items-center"><select value={closePayMethod} onChange={e => setClosePayMethod(e.target.value as PaymentMethod)} className="border rounded-lg px-3 py-2 text-sm"><option value="cash">Efectivo</option><option value="card">Tarjeta</option><option value="transfer">Transferencia</option></select><span className="text-gray-500">$</span><input type="number" value={closePayAmount} onChange={e => setClosePayAmount(e.target.value)} placeholder="0" className="flex-1 border rounded-lg px-3 py-2 text-sm" /><button onClick={() => setClosePayAmount('')} className="text-gray-400 hover:text-red-500">×</button></div></div>{closePayMethod === 'cash' && parseFloat(closePayAmount) > 0 && (<div className="bg-gray-50 rounded-lg px-4 py-3 flex justify-between"><span className="text-gray-600">Vuelta:</span><span className="text-lg font-bold">${fmt(Math.max(0, (parseFloat(closePayAmount) || 0) - selectedBoardOrder.total - (parseFloat(closeTipAmount) || 0)))}</span></div>)}</div><div className="px-6 py-4 border-t flex gap-3"><button onClick={() => { setShowCloseModal(false); setCloseTipAmount(''); setClosePayAmount(''); }} className="flex-1 py-2.5 rounded-xl border text-sm text-gray-600">Cancelar</button><button onClick={closeBoardOrder} className="flex-1 py-2.5 rounded-xl bg-orange-500 hover:bg-orange-600 text-white text-sm font-bold">Cerrar Pedido</button></div></div></div>)}

      {/* Product popup with images */}
      {showProductPopup && (<div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4"><div className="bg-white rounded-2xl shadow-2xl w-full max-w-4xl max-h-[80vh] flex flex-col"><div className="px-6 py-4 border-b flex items-center justify-between"><h2 className="text-lg font-bold">Seleccionar Producto</h2><button onClick={() => setShowProductPopup(false)} className="text-gray-400 hover:text-gray-600 text-xl">×</button></div><div className="px-6 py-3 border-b flex gap-2 overflow-x-auto"><button onClick={() => setPopupCategory('')} className={`px-3 py-1.5 rounded-full text-xs font-medium whitespace-nowrap ${!popupCategory ? 'bg-sushi-primary text-white' : 'bg-gray-100 text-gray-600'}`}>Todos</button>{categories.map(c => <button key={c} onClick={() => setPopupCategory(c)} className={`px-3 py-1.5 rounded-full text-xs font-medium whitespace-nowrap ${popupCategory === c ? 'bg-sushi-primary text-white' : 'bg-gray-100 text-gray-600'}`}>{c}</button>)}</div><div className="flex-1 overflow-y-auto p-4"><div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-3">{popupFiltered.map(item => (<button key={item._id} onClick={() => addToCart(item)} className="bg-white rounded-xl shadow-sm border p-2 text-left hover:shadow-md transition-all active:scale-95">{item.image_url ? <img src={item.image_url} alt={item.name} className="w-full h-24 object-cover rounded-lg mb-1" onError={e => { (e.target as HTMLImageElement).style.display = 'none'; }} /> : <div className="w-full h-24 bg-gray-100 rounded-lg mb-1 flex items-center justify-center text-xs text-gray-400">Sin imagen</div>}<p className="text-xs font-medium text-gray-900 truncate">{item.name}</p><p className="text-sm font-bold text-sushi-primary">${fmt(item.price)}</p></button>))}</div></div></div></div>)}

      {/* New customer modal */}
      {showNewCustomerModal && (<div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4"><div className="bg-white rounded-2xl shadow-2xl w-full max-w-md"><div className="px-6 py-4 border-b bg-gray-800 text-white rounded-t-2xl flex items-center justify-between"><h2 className="text-lg font-bold">NUEVO CLIENTE</h2><button onClick={() => setShowNewCustomerModal(false)} className="text-gray-300 hover:text-white text-xl">×</button></div><div className="px-6 py-4 space-y-3">
        <div><label className="block text-sm text-gray-700 mb-1">Nombre <span className="text-red-500">*</span></label><input value={newCustName} onChange={e => setNewCustName(e.target.value)} className="w-full border rounded-lg px-3 py-2 text-sm" /></div>
        <div><label className="block text-sm text-gray-700 mb-1">Teléfono</label><input value={newCustPhone} onChange={e => setNewCustPhone(e.target.value)} className="w-full border rounded-lg px-3 py-2 text-sm" /></div>
        <div><label className="block text-sm text-gray-700 mb-1">Email</label><input value={newCustEmail} onChange={e => setNewCustEmail(e.target.value)} className="w-full border rounded-lg px-3 py-2 text-sm" /></div>
        <div><label className="block text-sm text-gray-700 mb-1">Fecha de nacimiento</label><input type="date" value={newCustBirthday} onChange={e => setNewCustBirthday(e.target.value)} className="w-full border rounded-lg px-3 py-2 text-sm" /></div>
        <div><label className="block text-sm text-gray-700 mb-1">Nro. Tributario</label><input value={newCustRFC} onChange={e => setNewCustRFC(e.target.value)} placeholder="RFC" className="w-full border rounded-lg px-3 py-2 text-sm" /></div>
        <div><label className="block text-sm text-gray-700 mb-1">Comentario</label><textarea value={newCustComment} onChange={e => setNewCustComment(e.target.value)} className="w-full border rounded-lg px-3 py-2 text-sm" rows={3} /></div>
      </div><div className="px-6 py-4 border-t flex gap-3"><button onClick={() => setShowNewCustomerModal(false)} className="flex-1 py-2.5 rounded-xl border text-sm text-gray-600">Cancelar</button><button onClick={saveNewCustomer} disabled={!newCustName} className="flex-1 py-2.5 rounded-xl bg-orange-500 hover:bg-orange-600 disabled:opacity-50 text-white text-sm font-bold">Guardar</button></div></div></div>)}
    </div>
  );
};
export default POS;
